### ISSUE TITLE
move from python 2.6 to 2.7 or 3.6

### ISSUE THREAD

**Issue by stevemar** [IBM/connector-for-storediq#5]
@maheshwarishikha do we have a contact on the StoreIQ team that we can talk to? The fact that the siq_connector SDK is python 2.6 only will really limit this code patterns effectiveness. The last release of python 2.6 was in 2013 and the python community as a whole intends to EOL python 2.7 in 2020.

**Comment by maheshwarishikha** [comment]
@stevemart , I understand your concern and hence checked again with StoredIQ team. I got the following response :
"Right now it is Python 2.6. You cannot change it.
We have a plan to change it, most probably that will happen in 3 months, in our September release."

**Comment by stevemar** [comment]
@maheshwarishikha alright, we can revisit this in September. Did they mention what version of python they will support?

**Comment by maheshwarishikha** [comment]
@stevemart , they said,  "There is no plan to move to Python 3. Python 2 and Python 3 follows different syntax. So our plan is to move to the latest version of python 2".

**Comment by stevemar** [comment]
@maheshwarishikha each library is a different, but for the most part it's a few days work to make a code base python2 and python 3 compatible. I've done this for various libraries like [ldappool](https://github.com/openstack/ldappool/commit/5f6748212bf8eab46ec74cec6292fe48757162ce). The biggest hurdle is if a dependent library isn't py3 compatible yet, to which there are fewer and fewer everyday now. Anyway, happy to help estimate the effort or actually suggest code fixes for the code base.

**Comment by maheshwarishikha** [comment]
@stevemart , 
sure, will convey to StoredIQ team 👍 
So for time being we can go ahead to publish this pattern with Python 2.6...right?

**Comment by stevemar** [comment]
yap

**Comment by maheshwarishikha** [comment]
Thanks 👍
