### ISSUE TITLE
 [Reg_type.INVALID_MODULE] No module named svn_connector.svn_conn

### ISSUE THREAD

**Issue by nmaiya** [IBM/connector-for-storediq#7]
Hi,

I was just trying this connector while registering the connection I'm getting following error
I copied both the connectors to the site-package as mentioned 

> Traceback (most recent call last):
>   File "/usr/local/storediq/bin/register_connector.py", line 22, in <module>
>     cd.register(class_name, writable=write_enable)
>   File "/usr/lib/python2.6/site-packages/deepfile/registration/connregistrationfactory.py", line 163, in register
>     raise Exception(str(e))
> Exception: [Reg_type.INVALID_MODULE] No module named svn_connector.svn_conn

Bellow is the command I'm using for the registration

`python32 /usr/local/storediq/bin/register_connector.py -c svn_connector.svn_conn.SvnConnector`

I'm fairly new to StoredIQ and the Python, so when you are saying the module name are you referring it to the file which has connecter class?

**Comment by maheshwarishikha** [comment]
Hi @nmaiya , it seems to be some naming issue.
```
if your Connector folder is my_connector, class name is MyConnector and the module that defines the class is my_module, then class-path will be my_connector.my_module.MyConnector
```

Yes, module name is the filename which connector class.
Check the command output `python32 /usr/loca/storediq/bin/register_connector.py -h` for more information.

**Comment by maheshwarishikha** [comment]
Did it work for you?
